### ISSUE TITLE
mst2 is interrupted in Tutorial CuZn/BCC, but B2 and Supercell work fine

### ISSUE THREAD

**Issue by ysj7323** [mstsuite/MuST#17] opened 2022-02-27 09:18 UTC
I compiled MST/bin/mst2 (with arch/bolt_intel_O3) and no error warning was reported during compilation. Both B2 and Supercell of CuZn Tutorials can work.  However, when the random alloy of the CuZn-BCC directory is calculated, the calculation is interrupted and an error occurs as:

 mpirun -np 4 /home/zhouq/work/Must/MST/bin/mst2 <i_new > vout &
[1] 4777
[zhouq@y01]$ *** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000d51fe50 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000dea26b0***
    glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000d51fe50 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000dea26b0 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000dea26b0 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000d2f1e30 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000d2f1e30 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000ea75e50 ***
*** glibc detected *** /home/zhouq/work/Must/MST/bin/mst2: malloc(): memory corruption: 0x000000000ea75e50 ***

Also, the last lines of the o_n00000_CuZn file:

                             **********************
                             * Output from mufind *
                             **********************
At Old Fermi Energy
    GLOBAL VP Int[n(e)] per Atom       =   11.511893519396
    GLOBAL (Val-Int[n(e)]) per Site    =   -0.011893519396
    Fermi Energy DOS per Site          =    3.613883712604
    Specific Heat Coefficient per Site =    0.000000000477
    Magnetic Susceptibility per Site   =    0.000000000000
    Num Valence Electrons per Atom     =   11.500000000000

New Fermi energy                       =    0.638490358364
Change in Fermi energy                 =   -0.003291063117

After mufind, the integrated DOS are:
id =  1, ia =  1, is =  1, MS+SS  DOS_mt =  0.10334066D+02, MS+SS  DOS_ws =  0.11176943D+02
id =  1, ia =  2, is =  1, MS+SS  DOS_mt =  0.11008870D+02, MS+SS  DOS_ws =  0.11823057D+02

--------------------------------------------------------------------------------

Did I set the compilation options incorrectly?
thx

**Comment by wangy2014** [comment] 2022-02-27 16:13
Thank you for reporting the problem. There appears to be a bug in the latest code that has caused memory leak during the KKR-CPA calculation. I will look into this issue and will let you know once the bug is fixed.

**Comment by wangy2014** [comment] 2022-02-28 02:40
Thank you again for reporting the run-time error. The problem is now fixed, Please download and use the latest code release.

**Closed** 2022-02-28 02:41 UTC
